image: node:lts-slim

stages:
  - deploy

pages:
  stage: deploy
  script:
  - npm install --production  # 安装生产依赖
  - npm run build --prefix-paths  # 执行构建命令
  artifacts:
    paths:
      - public
  only:
    - main