image: node:14

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public  # Gatsby 默认的构建输出目录

pages:
  stage: deploy
  script:
    - mv public public_html  # 将构建输出目录重命名为 public_html
  artifacts:
    paths:
      - public_html